#!/bin/sh

VIDEO="$1"
AUDIO="$2"
ARGS="$3"

if (test "$1" = "")
then
  echo "Help:"
  echo "-Execute file in terminal and append 2-3 arguments:"
  echo "-(1=video source, 2=audio source, 3=ffmpeg arguments (eg. -t 00:05:00 for 5min duration))"
  echo "Example:"
  echo "-/bin/remux /video-source-folder /audio-source-folder -t 00:05:00"
  exit
fi

cd "$VIDEO"
mkdir remuxed

for i in *.*; do ffmpeg -hwaccel videotoolbox -i "$i" -i "$AUDIO""/${i%.*}."* $ARGS -map 0:v -map 1:a -c copy "remuxed/$i"; done
